let a=1;
let b=2;

console.log(a-b);


console.log(a-b);
console.log(a-b);

console.log(a-b);

console.log(a+b);

console.log(a*b);

try{

console.log(a*c);// here i will got a error so for this line error the next line of it if they are correct but they will not run for this error so if any time i have a doubt on that the code i written it will not work it will give me a error on that time we use try catch function so our next line kam kore jodi etat error thake
}catch(err){
// here this err argument is a object which catch the error of the code if any found otherwise it don't show any error 

    console.log(err);

}


console.log(a*b);

console.log(a*b);

console.log(a*b);


console.log(a*b);
console.log(a*b);
